// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class BonusInformationEntity
    {
        public int Id { get; set; }
        public string DecisionNumber { get; set; }
        public DateTime? DecisionDate { get; set; }
        public int? ThePersonSignedTheDecisionId { get; set; }
        public DateTime? BonusDay { get; set; }
        public int? RewardPlanId { get; set; }
        public string BonusGrounds { get; set; }
        public int? RewardReasonId { get; set; }
        public int? CommendationFormId { get; set; }
        public int? BonusBudgetSourceId { get; set; }
        public string TotalValue { get; set; }
        public int? StatusBonusId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
