// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class ContactInformationEntity
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public string MobilePhone { get; set; }
        public string OfficePhone { get; set; }
        public string HomePhone { get; set; }
        public string OtherPhone { get; set; }
        public string PersonalEmail { get; set; }
        public string CompanyEmail { get; set; }
        public string OtherEmail { get; set; }
        public string Skype { get; set; }
        public string Facebook { get; set; }
        public string Domicile { get; set; }
        public int? ProvinceCityId { get; set; }
        public string PlaceBirth { get; set; }
        public int? ResidenceNationalityId { get; set; }
        public int? ResidenceProvinceCityId { get; set; }
        public int? ResidenceDistrictId { get; set; }
        public int? ResidenceWardsId { get; set; }
        public string ResidenceHouseStreetVillageNumber { get; set; }
        public string ResidenceAddress { get; set; }
        public string ResidenceHouseholdRegistrationNumber { get; set; }
        public string ResidenceHouseholdCode { get; set; }
        public bool? ResidenceIsHeadHousehold { get; set; }
        public int? CurrentNationalityId { get; set; }
        public int? CurrentProvinceCityId { get; set; }
        public int? CurrentDistrictId { get; set; }
        public int? CurrentWardsId { get; set; }
        public string CurrentHouseStreetVillageNumber { get; set; }
        public string CurrentAddress { get; set; }
        public string UrgentContactFirstAndLastName { get; set; }
        public int? UrgentContactRelationshipId { get; set; }
        public string UrgentContactMobilePhone { get; set; }
        public string UrgentContactHomePhone { get; set; }
        public string UrgentContactEmail { get; set; }
        public string UrgentContactAddress { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
