// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class FunctionsEntity
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Caption { get; set; }
        public long? ParentId { get; set; }
        public bool? Enable { get; set; }
        public string NodePath { get; set; }
        public string Url { get; set; }
        public int? Order { get; set; }
        public bool? IsApi { get; set; }
        public string Icon { get; set; }
        public bool? IsShow { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
