// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class NationalityEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
#pragma warning restore 1591
