// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class ResignationProceduresEmployeeDebtEntity
    {
        public int Id { get; set; }
        public int? ResignationProceduresId { get; set; }
        public int? NameOfTheDebtId { get; set; }
        public string AmountOfMoney { get; set; }
        public DateTime? FinishDay { get; set; }
        public bool? Accomplished { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
