// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.TypedEntities
{
    public class TypeProblemInformation : IUserDefinedType
    {
        public int Id { get; set; }
        public string ProblemName { get; set; }
        public int? TypeOfIncidentId { get; set; }
        public DateTime? HappenDay { get; set; }
        public string WhereHappened { get; set; }
        public string Reason { get; set; }
        public string DescriptionOfTheProblem { get; set; }
        public int? RelatedUnitId { get; set; }
        public string TotalValueOfDamage { get; set; }
        public string TotalCompensationValue { get; set; }
        public int? CompensationStatusId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
