// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.TypedEntities
{
    public class TypeJobInformation : IUserDefinedType
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public string TimekeepingCode { get; set; }
        public int? WorkStatusId { get; set; }
        public int? DirectManagementId { get; set; }
        public int? IndirectManagementId { get; set; }
        public int? WorkLocationId { get; set; }
        public string LaborManagementBookNumber { get; set; }
        public int? ContractTypeId { get; set; }
        public DateTime? ApprenticeDay { get; set; }
        public DateTime? ProbationDay { get; set; }
        public DateTime? OfficialDate { get; set; }
        public string NumberOfDaysOff { get; set; }
        public bool? AutomaticallyIncreasesMagicAccordingToSeniority { get; set; }
        public string IncreaseLaterSpells { get; set; }
        public int? WageId { get; set; }
        public string BasicSalary { get; set; }
        public string InsurancePremiums { get; set; }
        public string StandardPublicNumber { get; set; }
        public int? StandardPublicId { get; set; }
        public string BankAccoun { get; set; }
        public int? BankId { get; set; }
        public bool? JoinTheUnion { get; set; }
        public DateTime? DateOfInsurance { get; set; }
        public string InsurancePremiumRate { get; set; }
        public string SomeSocialInsuranceBooks { get; set; }
        public string SocialInsuranceNumber { get; set; }
        public string ProvinceCodeLevel { get; set; }
        public int? ProvinceNameLevelId { get; set; }
        public string HealthInsuranceCardNumber { get; set; }
        public DateTime? HealthInsuranceExpirationDate { get; set; }
        public int? PlaceOfRegistrationForMedicalExaminationAndTreatmentId { get; set; }
        public string CodesOfMedicalExaminationAndTreatmentPlaces { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
