// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.TypedEntities
{
    public class TypeDegreeInformation : IUserDefinedType
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public int? TrainingPlacesId { get; set; }
        public string FromYear { get; set; }
        public string ToYear { get; set; }
        public int? FacultyId { get; set; }
        public int? SpecializedId { get; set; }
        public int? DegreeTrainingId { get; set; }
        public int? FormsOfTrainingId { get; set; }
        public int? ClassificationId { get; set; }
        public bool? Graduated { get; set; }
        public DateTime? DateReceived { get; set; }
        public string Note { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
