// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class AllowanceInformationEntity
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public int? AllowanceTypeId { get; set; }
        public string Price { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? ToDate { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
