// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class EmployeeInformationEntity
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public int? SexId { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string PersonalTaxCode { get; set; }
        public int? WorkUnitId { get; set; }
        public int? JobPositionId { get; set; }
        public int? NationId { get; set; }
        public int? ReligionId { get; set; }
        public int? NationalityId { get; set; }
        public string IdentificationCardNumber { get; set; }
        public DateTime? DateOfIssueOfIdentificationCard { get; set; }
        public string PlaceOfIssueOfIdCard { get; set; }
        public DateTime? IdentificationCardExpirationDate { get; set; }
        public string PassportNumber { get; set; }
        public DateTime? PassportDate { get; set; }
        public string PlaceOfIssueOfPassport { get; set; }
        public DateTime? PassportExpirationDate { get; set; }
        public int? EducationalLevelId { get; set; }
        public int? DegreeTrainingId { get; set; }
        public int? TrainingPlacesId { get; set; }
        public int? FacultyId { get; set; }
        public int? SpecializedId { get; set; }
        public string GraduationYear { get; set; }
        public int? ClassificationId { get; set; }
        public int? MaritalStatusId { get; set; }
        public int? FamilyMemberId { get; set; }
        public int? IngredientsThemselvesId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
