// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class EvaluateEntity
    {
        public int Id { get; set; }
        public string NameOfAudit { get; set; }
        public int? EvaluationPeriodId { get; set; }
        public int? WorkUnitId { get; set; }
        public int? EvaluationStatusId { get; set; }
        public int? PersonInChargeId { get; set; }
        public DateTime? Since { get; set; }
        public DateTime? ToDate { get; set; }
        public DateTime? EvaluationTerm { get; set; }
        public string BriefDescription { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
