// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class PoliticsHealthMilitaryInformationEntity
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public bool? IsAUnionMember { get; set; }
        public DateTime? DayToUnion { get; set; }
        public int? GroupPositionId { get; set; }
        public string PlaceOfUnionAdmission { get; set; }
        public bool? AsAPartyMember { get; set; }
        public DateTime? DayToParty { get; set; }
        public int? PartyPositionId { get; set; }
        public string PlaceOfAdmissionToTheParty { get; set; }
        public int? BloodGroupId { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string HealthStatus { get; set; }
        public string Diseases { get; set; }
        public string Note { get; set; }
        public bool? PeopleWithDisabilities { get; set; }
        public bool? AsASsoldier { get; set; }
        public DateTime? DateOfEnlistment { get; set; }
        public int? ArmyId { get; set; }
        public string MilitaryUnit { get; set; }
        public int? MilitaryRankId { get; set; }
        public int? MilitaryPositionId { get; set; }
        public DateTime? DateOfDemobilization { get; set; }
        public string TheReason { get; set; }
        public bool? AsWoundedSoldiersSickSoldiers { get; set; }
        public DateTime? DateToJoinRevolution { get; set; }
        public int? RankId { get; set; }
        public string RateOfLaborDecline { get; set; }
        public bool? EnjoyTheMode { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
