// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class ProblemInformationRelatedStaffEntity
    {
        public int Id { get; set; }
        public int? ProblemInformationId { get; set; }
        public int? EmployeeId { get; set; }
        public string DescribeTheRelationship { get; set; }
        public string TotalNumberOfDaysOffDueToOccupationalAccidents { get; set; }
        public int? InjuryConditionId { get; set; }
        public int? ProcessingStatusId { get; set; }
        public bool? HavePassedLaborSafetyTraining { get; set; }
        public string DecisionNumber { get; set; }
        public DateTime? DecisionDate { get; set; }
        public int? KindOfDecisionId { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public int? FormsProcessingId { get; set; }
        public int? TheDecisionId { get; set; }
        public string CitationOfContent { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
