// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class SkinInformationEntity
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public int? ShirtStringId { get; set; }
        public int? TrousersStringId { get; set; }
        public int? ZuypStringId { get; set; }
        public int? ProtectiveGearStringId { get; set; }
        public int? ShirtNumberId { get; set; }
        public int? TrousersNumberId { get; set; }
        public int? ZuypNumberId { get; set; }
        public int? ProtectiveGearNumberId { get; set; }
        public string ShoulderWidth { get; set; }
        public string LongSleeve { get; set; }
        public string LongCoat { get; set; }
        public string ChestRing { get; set; }
        public string Waist { get; set; }
        public string Buttocks { get; set; }
        public string LongPants { get; set; }
        public string LongSkirt { get; set; }
        public string LapThigh { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
