// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class TrainingProcessInformationEntity
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public string TrainingProcessCode { get; set; }
        public string TrainingProcessName { get; set; }
        public DateTime? StartDay { get; set; }
        public DateTime? EndDate { get; set; }
        public string Purpose { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
