// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.Entity
{
    public class WorkExperienceInformationEntity
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public DateTime? FromMonthAndYear { get; set; }
        public DateTime? ByMonthAndYear { get; set; }
        public string Workplace { get; set; }
        public string JobPosition { get; set; }
        public string Wage { get; set; }
        public string JobDescription { get; set; }
        public string Note { get; set; }
        public string FirstAndLastName { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public bool? HaveCheckedCompared { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
