// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.TypedEntities
{
    public class TypeFamilyInformation : IUserDefinedType
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public int? RelationshipId { get; set; }
        public string FirstAndLastName { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public int? SexId { get; set; }
        public int? NationalityId { get; set; }
        public string IdPassportNumber { get; set; }
        public string Address { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string Email { get; set; }
        public string Job { get; set; }
        public string PersonalTaxCode { get; set; }
        public string Workplace { get; set; }
        public bool? SameHouseholdRegistrationBook { get; set; }
        public bool? BeTheHeadOfTheHousehold { get; set; }
        public bool? IsADependent { get; set; }
        public DateTime? TimeToCalculateDeduction { get; set; }
        public DateTime? TimeToEndTheDeduction { get; set; }
        public string Note { get; set; }
        public bool? IsDead { get; set; }
        public DateTime? DeadDate { get; set; }
        public bool? AsAnEmergencyContact { get; set; }
        public string Number { get; set; }
        public string NumberBook { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
