// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.TypedEntities
{
    public class TypeEvaluateDetail : IUserDefinedType
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public int? EvaluateId { get; set; }
        public string Result { get; set; }
        public string EvaluateStatus { get; set; }
        public string ResultJson { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
