// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.TypedEntities
{
    public class TypeEmployeesOnBusinessTripRevenueEstimates : IUserDefinedType
    {
        public int Id { get; set; }
        public int? EmployeesOnBusinessTripId { get; set; }
        public string Revenue { get; set; }
        public string AmountOfMoney { get; set; }
        public string Note { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
