// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.TypedEntities
{
    public class TypeContractInformation : IUserDefinedType
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public int? JobPositionId { get; set; }
        public string SomeContracts { get; set; }
        public int? WorkUnitId { get; set; }
        public DateTime? SignDay { get; set; }
        public string ContractName { get; set; }
        public int? ContractTypeId { get; set; }
        public int? ContractTermId { get; set; }
        public int? TheFormOfWorkId { get; set; }
        public string WageRate { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public string Abstract { get; set; }
        public string Note { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
