// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.TypedEntities
{
    public class TypeEmployeesOnBusinessTrip : IUserDefinedType
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public int? EmployeeApprovedId { get; set; }
        public DateTime? DayTo { get; set; }
        public DateTime? ReturnDate { get; set; }
        public string WorkingPlace { get; set; }
        public string WorkingPurpose { get; set; }
        public DateTime? RecommendedDate { get; set; }
        public DateTime? Deadline { get; set; }
        public string AmountProposedForAdvance { get; set; }
        public string AmountOfAdvance { get; set; }
        public string ReasonForAdvance { get; set; }
        public string RequireToBeSupported { get; set; }
        public int? BrowsingStatusId { get; set; }
        public string ReasonsForNotBrowsing { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
