// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.TypedEntities
{
    public class TypePageInformation : IUserDefinedType
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public string NameOfPapers { get; set; }
        public string IssuedBy { get; set; }
        public DateTime? DateRange { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public string Note { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
