// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace NHIGIA.Core.Domain.TypedEntities
{
    public class TypeResignationProcedures : IUserDefinedType
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public DateTime? ExpectedResignationDate { get; set; }
        public string Note { get; set; }
        public string DecisionNumber { get; set; }
        public DateTime? DecisionDate { get; set; }
        public DateTime? DayOff { get; set; }
        public int? ReviewerId { get; set; }
        public string ReasonForRest { get; set; }
        public string Comments { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
#pragma warning restore 1591
